### ISSUE TITLE
The plugin is giving errors and breaking the batch import of metadata when using it

### ISSUE THREAD

**Issue by ferrazpedro** [cooperate/SteamGridDBMetadata#6]
Good Evening!
When I try to download metadata in batches with the plugin enabled, a lot of times it just completely breaks the process for some games and gives this in my log:

[Error - 14072020.log](https://github.com/cooperate/SteamGridDBMetadata/files/4777721/Error.-.14072020.log)

**Comment by cooperate** [comment]
I'll take a look @ferrazpedro thanks for posting the issue.

**Comment by shakeyourbunny** [comment]
This should not happen, if there is some basic problem, like not finding the game, the extension should not crash and burn and stopping other metadata extensions to continue searching.

```
2020-07-28 17:13:14.2918|DEBUG:Downloading metadata for Alien Breed: Tower Assault, 1207663753, aebe8b7c-6dc3-4a66-af31-e7375c6b5e9e
2020-07-28 17:13:14.7981|DEBUG:Downloading string content from http://api.gog.com/products/1207663753?expand=description using cookies and System.Text.UTF8Encoding encoding.
2020-07-28 17:13:15.9000|INFO:SGDB Initialized
2020-07-28 17:13:15.9000|INFO:AvailableFields
2020-07-28 17:13:15.9000|INFO:GetAvailableFields
2020-07-28 17:13:15.9000|INFO:https://www.steamgriddb.com/api/v2/heroes/gog/1207663753
2020-07-28 17:13:16.1056|INFO:{"success":false,"status":404,"errors":["Game not found"]}
2020-07-28 17:13:16.1056|DEBUG:Copying file bad path to D:\Client\PlayNite\7\library\files\74e0d2e4-8c98-4fda-866e-1b80c0fc2944\07e6e307-50c2-45ca-9436-3b3e87b30903
2020-07-28 17:13:16.1056|ERROR:Failed to copy file bad path to database.System.IO.FileNotFoundException: Could not find file 'bad path'.
File name: 'bad path'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Playnite.Common.FileSystem.CopyFile(String sourcePath, String targetPath, Boolean overwrite)
   at Playnite.Database.GameDatabase.AddFile(String path, Guid parentId) in E:\Devel\Playnite\source\Playnite\Database\GameDatabase.cs:line 379
2020-07-28 17:13:16.1056|INFO:AvailableFields
2020-07-28 17:13:16.1056|INFO:GetCoverImage
2020-07-28 17:13:16.1056|INFO:https://www.steamgriddb.com/api/v2/grids/gog/1207663753?dimensions=600x900&styles=alternate
2020-07-28 17:13:16.3262|INFO:{"success":false,"status":404,"errors":["Game not found"]}
2020-07-28 17:13:16.3262|DEBUG:Copying file bad path to D:\Client\PlayNite\7\library\files\74e0d2e4-8c98-4fda-866e-1b80c0fc2944\69443918-2c6a-433e-899a-f41cc5950694
2020-07-28 17:13:16.3262|ERROR:Failed to copy file bad path to database.System.IO.FileNotFoundException: Could not find file 'bad path'.
File name: 'bad path'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Playnite.Common.FileSystem.CopyFile(String sourcePath, String targetPath, Boolean overwrite)
   at Playnite.Database.GameDatabase.AddFile(String path, Guid parentId) in E:\Devel\Playnite\source\Playnite\Database\GameDatabase.cs:line 379
```

**Comment by cooperate** [comment]
@shakeyourbunny @ferrazpedro The issue should be resolved now in the latest release (v0.5.1).  Please test and report back any errors you might find.  Thanks!

**Comment by shakeyourbunny** [comment]
Not quite.

After manually updating 1954 Alcatraz, this happens in the log:
```
2020-07-30 21:57:59.5707|INFO:GetCoverImage
2020-07-30 21:57:59.5707|INFO:https://www.steamgriddb.com/api/v2/grids/steam/255280?dimensions=600x900&styles=alternate
2020-07-30 21:57:59.7883|INFO:{"success":true,"data":[{"id":71103,"score":0,"style":"alternate","nsfw":false,"humor":false,"notes":null,"language":"en","url":"https:\/\/cdn.steamgriddb.com\/grid\/209ec9c46bf5f37ad7f0119b023ce906.png","thumb":"https:\/\/cdn.steamgriddb.com\/thumb\/209ec9c46bf5f37ad7f0119b023ce906.png","author":{"name":"HydraCleave","steam64":"76561198102966368","avatar":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/50\/50a26e78a22b0f919188e0528a1222a30a974b2e.jpg"}}]}
2020-07-30 21:57:59.7883|ERROR:Failed to download metadata for game 1954 Alcatraz, 09e9d157-81b2-4ac9-a719-8cc7d88fbc2cSystem.Exception: Cannot add file, no file data provided.
   at Playnite.Database.GameDatabase.AddFile(MetadataFile file, Guid parentId) in E:\Devel\Playnite\source\Playnite\Database\GameDatabase.cs:line 341
   at Playnite.Metadata.MetadataDownloader.<>c__DisplayClass10_0.<DownloadMetadataAsync>b__0() in E:\Devel\Playnite\source\Playnite\Metadata\MetadataDownloader.cs:line 451
```

Also
```
2020-07-30 22:04:54.2509|INFO:SGDB Initialized
2020-07-30 22:04:54.2509|INFO:AvailableFields
2020-07-30 22:04:54.2509|INFO:GetAvailableFields
2020-07-30 22:04:54.2509|INFO:https://www.steamgriddb.com/api/v2/heroes/steam/831810
2020-07-30 22:04:54.5246|INFO:{"success":true,"data":[]}
2020-07-30 22:04:54.5246|DEBUG:Downloading data from https://steamcdn-a.akamaihd.net/steam/apps/831810/ss_5eba29eba2ea4e59ae08cdb6eb6a58490b9a6d55.1920x1080.jpg to D:\Client\PlayNite\7\library\files\d8d0cd79-a260-495f-9bbc-7c6be498b2d5\6908c3dc-0d51-4529-afdb-efee25757cbd.jpg.
2020-07-30 22:04:54.8765|INFO:AvailableFields
2020-07-30 22:04:54.8765|INFO:GetCoverImage
2020-07-30 22:04:54.8765|INFO:https://www.steamgriddb.com/api/v2/grids/steam/831810?dimensions=600x900&styles=alternate
2020-07-30 22:04:55.0871|INFO:{"success":true,"data":[{"id":87396,"score":0,"style":"alternate","nsfw":false,"humor":false,"notes":null,"language":"en","url":"https:\/\/cdn.steamgriddb.com\/grid\/20ad8203416b5e12f26d580be7e34472.png","thumb":"https:\/\/cdn.steamgriddb.com\/thumb\/20ad8203416b5e12f26d580be7e34472.png","author":{"name":"shakeyourbunny","steam64":"76561198055778112","avatar":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/52\/5234d2725ba02e2cae7f137e328c9c18fbffb92c.jpg"}}]}
2020-07-30 22:04:55.0871|ERROR:Failed to download metadata for game Bane of Asphodel, d8d0cd79-a260-495f-9bbc-7c6be498b2d5System.Exception: Cannot add file, no file data provided.
   at Playnite.Database.GameDatabase.AddFile(MetadataFile file, Guid parentId) in E:\Devel\Playnite\source\Playnite\Database\GameDatabase.cs:line 341
   at Playnite.Metadata.MetadataDownloader.<>c__DisplayClass10_0.<DownloadMetadataAsync>b__0() in E:\Devel\Playnite\source\Playnite\Metadata\MetadataDownloader.cs:line 451
2020-07-30 22:04:55.1954|INFO:[router] [info] Initiating graceful butlerd shutdown
```
In this case, the cover image was uploaded some time ago to steamgriddb and should have been downloaded properly.

The game itself is a free game on Steam btw.

**Comment by cooperate** [comment]
Should be good to go now!  Thanks for the quick response.  See https://github.com/cooperate/SteamGridDBMetadata/releases/tag/v0.5.2

**Comment by shakeyourbunny** [comment]
Seems to work now.

```
2020-07-31 15:49:18.2645|INFO:SGDB Initialized
2020-07-31 15:49:18.2645|INFO:AvailableFields
2020-07-31 15:49:18.2645|INFO:GetAvailableFields
2020-07-31 15:49:18.2956|INFO:https://www.steamgriddb.com/api/v2/heroes/steam/831810
2020-07-31 15:49:18.9553|INFO:{"success":true,"data":[]}
2020-07-31 15:49:18.9633|DEBUG:Downloading data from https://steamcdn-a.akamaihd.net/steam/apps/831810/ss_5eba29eba2ea4e59ae08cdb6eb6a58490b9a6d55.1920x1080.jpg to D:\Client\PlayNite\7\library\files\d8d0cd79-a260-495f-9bbc-7c6be498b2d5\7c241440-2f2a-4586-a502-335c2d62ce84.jpg.
2020-07-31 15:49:19.1268|INFO:AvailableFields
2020-07-31 15:49:19.1308|INFO:GetCoverImage
2020-07-31 15:49:19.1308|INFO:https://www.steamgriddb.com/api/v2/grids/steam/831810?dimensions=600x900&styles=alternate
2020-07-31 15:49:19.3534|INFO:{"success":true,"data":[{"id":87396,"score":0,"style":"alternate","nsfw":false,"humor":false,"notes":null,"language":"en","url":"https:\/\/cdn.steamgriddb.com\/grid\/20ad8203416b5e12f26d580be7e34472.png","thumb":"https:\/\/cdn.steamgriddb.com\/thumb\/20ad8203416b5e12f26d580be7e34472.png","author":{"name":"shakeyourbunny","steam64":"76561198055778112","avatar":"https:\/\/steamcdn-a.akamaihd.net\/steamcommunity\/public\/images\/avatars\/52\/5234d2725ba02e2cae7f137e328c9c18fbffb92c.jpg"}}]}
2020-07-31 15:49:19.3644|DEBUG:Downloading data from https://cdn.steamgriddb.com/grid/20ad8203416b5e12f26d580be7e34472.png to D:\Client\PlayNite\7\library\files\d8d0cd79-a260-495f-9bbc-7c6be498b2d5\54bd3543-92e5-447e-a42d-b9a3bab06c19.png.
2020-07-31 15:49:19.7504|DEBUG:Downloading data from https://steamcdn-a.akamaihd.net/steamcommunity/public/images/apps/831810/c9a06ece4fd6a3b7da65dba58dc3ad5634c2bd66.ico to D:\Client\PlayNite\7\library\files\d8d0cd79-a260-495f-9bbc-7c6be498b2d5\60de2d3b-2d76-4498-8eb6-532eb5255674.ico.
2020-07-31 15:49:20.0773|INFO:[router] [info] Initiating graceful butlerd shutdown
2020-07-31 15:49:20.0773|INFO:[router] [info] While shutting down, request 805682442 has completed
2020-07-31 15:49:20.0773|INFO:[router] [info] No in-flight requests left, we can shut down now.
2020-07-31 15:49:20.0773|DEBUG:Butler: Closing TCP listener...
2020-07-31 15:49:20.0773|DEBUG:Butler: While accepting connection: accept tcp 127.0.0.1:61317: use of closed network connection
2020-07-31 15:49:20.0773|DEBUG:Butler: Waiting for TCP connections to close...
2020-07-31 15:49:20.1274|DEBUG:Butler: All TCP connections closed
```

Thank you for your efforts!

**Comment by shakeyourbunny** [comment]
It seems, the SGDB metadata extensions seems only work with Steam games, which is a bummer.

**Epic**: does not work (see above)
**Battle.net**: does not work
```
2020-07-31 17:30:41.2296|INFO:SGDB Initialized
2020-07-31 17:30:41.2296|INFO:AvailableFields
2020-07-31 17:30:41.2296|INFO:GetAvailableFields
2020-07-31 17:30:41.2296|INFO:GetCoverImage
2020-07-31 17:30:41.2296|INFO:https://www.steamgriddb.com/api/v2/grids/battle.net/S2?dimensions=600x900&styles=alternate

--> 404
```

**GOG**: seems to work.

**itch.io**: does not work.
```
2020-07-31 17:40:19.5630|INFO:SGDB Initialized
2020-07-31 17:40:19.5630|INFO:AvailableFields
2020-07-31 17:40:19.5630|INFO:GetAvailableFields
2020-07-31 17:40:19.5630|INFO:https://www.steamgriddb.com/api/v2/logos/itch.io/498716
```

**twitch**: does not work.
```
2020-07-31 17:43:43.1927|DEBUG:Downloading metadata for Tales from Candlekeep: Tomb of Annihilation, 9b00692d-1f3d-4d0e-ac1d-105ea177de81, e2a7d494-c138-489d-bb3f-1d786beeb675
2020-07-31 17:43:46.0313|DEBUG:Downloading string content from https://store.steampowered.com/api/appdetails?appids=663380&l=english using System.Text.UTF8Encoding encoding.
2020-07-31 17:43:46.5226|DEBUG:Downloading data from https://images.igdb.com/igdb/image/upload/t_original/ar6vl.jpg to D:\Client\PlayNite\7\library\files\89455d72-bcf2-445c-9b9a-6d3e78678329\5aff600a-6233-4b67-8b91-50bfb58a6a94.jpg.
2020-07-31 17:43:47.6556|INFO:SGDB Initialized
2020-07-31 17:43:47.6556|INFO:AvailableFields
2020-07-31 17:43:47.6556|INFO:GetAvailableFields
2020-07-31 17:43:47.6556|INFO:GetCoverImage
2020-07-31 17:43:47.6556|INFO:https://www.steamgriddb.com/api/v2/grids/twitch/9b00692d-1f3d-4d0e-ac1d-105ea177de81?dimensions=600x900&styles=alternate
2020-07-31 17:43:47.8571|INFO:<!DOCTYPE html>
```

**steam**: seems to work (with 0.5.2).


As I don't own accounts for Origin, UPlay, Bethesda, XBox or I don't trust the library importer (HumbleBundle), I strongly suspect that searching for metadata for these libraries are broken too.

**Comment by vannessqn** [comment]
I tried with Katawa Shoujo, service failure

**Comment by cooperate** [comment]
@shakeyourbunny @vannessqn this was an api issue, not a plugin issue.  If you don't mind try again to see if it's working.

**Comment by shakeyourbunny** [comment]
Nope, just tried it with several games from libraries from not Steam or GOG; same issue is persisting.

**Comment by cooperate** [comment]
@shakeyourbunny  I see what you're saying now yep!  I'll need to an exception for supported platforms as it's definitley causing issues.  I wouldn't be surprised if the memory leak is related to spam in the logs from that markup but it might not be.

**Comment by cooperate** [comment]
@shakeyourbunny https://github.com/cooperate/SteamGridDBMetadata/releases/tag/0.5.3

It falls back to my "fuzzy search" now if the game platform is not available.  Until I find time to find a more elegant solution (ie "this game is probably not available, let's not download the art for game y on game x) this should probably do the trick.

Test and verify.

Thanks for your help!

**Comment by shakeyourbunny** [comment]
Seems to be working now, thank you for your efforts!

**Comment by cooperate** [comment]
Closing this.
