### ISSUE TITLE
Automatic scraping not working when source set to null

### ISSUE THREAD

**Issue by PlayingKarrde** [cooperate/SteamGridDBMetadata#8]
Manual scraping works fine on individual games, but games that have no source set (ie emulated games) will cause the plugin to throw an error such as this:

`2020-10-09 17:16:35.1049|ERROR:Failed to download metadata for game NBA Showtime - NBA on NBC, 39c07cde-5e80-44b8-a61d-a14c219df79dSystem.NullReferenceException: Object reference not set to an instance of an object.
   at SGDBMetadata.SGDBMetadataProvider.GetBackgroundImage() in U:\App_Dev\SGDBMetadata\SGDBMetadata\SGDBMetadata\SGDBMetadataProvider.cs:line 112
   at Playnite.Metadata.MetadataDownloader.ProcessField(Game game, MetadataFieldSettings fieldSettings, MetadataField gameField, Func`2 propertySelector, Dictionary`2 existingStoreData, Dictionary`2 existingPluginData) in E:\Devel\Playnite\source\Playnite\Metadata\MetadataDownloader.cs:line 216
   at Playnite.Metadata.MetadataDownloader.<>c__DisplayClass10_0.<DownloadMetadataAsync>b__0() in E:\Devel\Playnite\source\Playnite\Metadata\MetadataDownloader.cs:line 423`

The fix appears to be to set the Source of the game to something other than null.

**Comment by cooperate** [comment]
I'll investigate this thanks.

**Comment by cooperate** [comment]
Should be corrected now on 0.5.5, test and verify. @PlayingKarrde

**Comment by PlayingKarrde** [comment]
Unfortunately, under Playnite 8.1, the plugin is not showing as a source when scraping multiple games. It shows fine when scraping individual though but I'm unable to test due to this.

**Comment by PlayingKarrde** [comment]
Confirmed to be working. Thanks.
